version: "3.0"

services:
  tml:
    container_name: tml
    restart: unless-stopped
    build:
      context: .
      # args:
      #   TMLVERSION: v2023.8.3.3
      #   UID: 1000
      #   GID: 1000
    ports:
      - 7777:7777
    volumes:
      - ./tModLoader:/data
      # Optional volumes below. These files/folders MUST exist on the host
      # before they can be mounted, otherwise they will appear as owned by root
      #- ./tModLoader/logs:/home/tml/server/tModLoader-Logs
      #- ./tModLoader/banlist.txt:/home/tml/server/banlist.txt
      #- ./tModLoader/cli-argsConfig.txt:/home/tml/server/cli-argsConfig.txt
